-- Raw data to give to Excel to generate the pivot table

SELECT
  CASE
    WHEN p.score BETWEEN 1 AND 10 THEN 'Group 1: 1 - 10'
    WHEN p.score BETWEEN 11 AND 20 THEN 'Group 2: 11 - 20'
    WHEN p.score BETWEEN 21 AND 30 THEN 'Group 3: 21 - 30'
    WHEN p.score BETWEEN 31 AND 40 THEN 'Group 4: 31 - 40'
    WHEN p.score BETWEEN 41 AND 50 THEN 'Group 5: 41 - 50'
    WHEN p.score BETWEEN 51 AND 60 THEN 'Group 6: 51 - 60'
    WHEN p.score BETWEEN 61 AND 70 THEN 'Group 7: 61 - 70'
    WHEN p.score BETWEEN 71 AND 80 THEN 'Group 8: 71 - 80'
    WHEN p.score BETWEEN 81 AND 90 THEN 'Group 9: 81 - 90'
    WHEN p.score BETWEEN 91 AND 100 THEN 'Group 10: 91 - 100'
    WHEN p.score BETWEEN 101 AND 110 THEN 'Group 11: 101 - 110'
    WHEN p.score BETWEEN 111 AND 120 THEN 'Group 12: 111 - 120'
    WHEN p.score BETWEEN 121 AND 130 THEN 'Group 13: 121 - 130'
    WHEN p.score BETWEEN 131 AND 140 THEN 'Group 14: 131 - 140'
    WHEN p.score BETWEEN 141 AND 150 THEN 'Group 15: 141 - 150'
    WHEN p.score BETWEEN 151 AND 160 THEN 'Group 16: 151 - 160'
    WHEN p.score BETWEEN 161 AND 170 THEN 'Group 17: 161 - 170'
    WHEN p.score BETWEEN 171 AND 180 THEN 'Group 18: 171 - 180'
    WHEN p.score BETWEEN 181 AND 190 THEN 'Group 19: 181 - 190'
    WHEN p.score BETWEEN 191 AND 200 THEN 'Group 20: 191 - 200'
    WHEN p.score BETWEEN 201 AND 210 THEN 'Group 21: 201 - 210'
    WHEN p.score BETWEEN 211 AND 220 THEN 'Group 22: 211 - 220'
    WHEN p.score BETWEEN 221 AND 230 THEN 'Group 23: 221 - 230'
    WHEN p.score BETWEEN 231 AND 240 THEN 'Group 24: 231 - 240'
    WHEN p.score BETWEEN 241 AND 250 THEN 'Group 25: 241 - 250'
    WHEN p.score BETWEEN 251 AND 260 THEN 'Group 26: 251 - 260'
    WHEN p.score BETWEEN 261 AND 270 THEN 'Group 27: 261 - 270'
    WHEN p.score BETWEEN 271 AND 280 THEN 'Group 28: 271 - 280'
    WHEN p.score BETWEEN 281 AND 290 THEN 'Group 29: 281 - 290'
    WHEN p.score BETWEEN 291 AND 300 THEN 'Group 30: 291 - 300'
    ELSE 'Group 31: n > 300' END AS score_group,
  CASE
    WHEN p.score BETWEEN 1 AND 50 THEN 'Group 1: 1 - 50'
    WHEN p.score BETWEEN 51 AND 100 THEN 'Group 2: 51 - 100'
    WHEN p.score BETWEEN 101 AND 150 THEN 'Group 3: 101 - 150'
    WHEN p.score BETWEEN 151 AND 200 THEN 'Group 4: 151 - 200'
    WHEN p.score BETWEEN 201 AND 250 THEN 'Group 5: 201 - 250'
    WHEN p.score BETWEEN 251 AND 300 THEN 'Group 6: 251 - 300'
    WHEN p.score BETWEEN 301 AND 350 THEN 'Group 7: 301 - 350'
    WHEN p.score BETWEEN 351 AND 400 THEN 'Group 8: 351 - 400'
    WHEN p.score BETWEEN 401 AND 450 THEN 'Group 9: 401 - 450'
    WHEN p.score BETWEEN 451 AND 500 THEN 'Group 10: 451 - 500'
    WHEN p.score BETWEEN 501 AND 550 THEN 'Group 11: 501 - 550'
    WHEN p.score BETWEEN 551 AND 600 THEN 'Group 12: 551 - 600'
    WHEN p.score BETWEEN 601 AND 650 THEN 'Group 13: 601 - 650'
    WHEN p.score BETWEEN 651 AND 700 THEN 'Group 14: 651 - 700'
    WHEN p.score BETWEEN 701 AND 750 THEN 'Group 15: 701 - 750'
    WHEN p.score BETWEEN 751 AND 800 THEN 'Group 16: 751 - 800'
    WHEN p.score BETWEEN 801 AND 850 THEN 'Group 17: 801 - 850'
    WHEN p.score BETWEEN 851 AND 900 THEN 'Group 18: 851 - 900'
    WHEN p.score BETWEEN 901 AND 950 THEN 'Group 19: 901 - 950'
    WHEN p.score BETWEEN 951 AND 1000 THEN 'Group 20: 951 - 1000'
    ELSE 'Group 21: n > 750' END AS length_group,
  _id AS ID,
  CHAR_LENGTH(p.content_text) AS text_length,
  p.score as score
FROM posts p
INTO OUTFILE '/var/lib/mysql-files/pivot.csv'
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'




-- Each row has a counter ID

-- TURN THIS INTO GENERATED BY JAVASCRIPT

SELECT ${counter} AS counter,
            COUNT(*) AS countOf,
            a.countOf,
            b.countOf
FROM posts p
INNER JOIN (
  SELECT ${counter} AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 1 AND 50
    AND p.score < 1
) AS a ON a.tmpid = ${counter}
INNER JOIN (
  SELECT 1 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 51 AND 100
    AND p.score < 1
) AS b ON b.tmpid = ${counter}
WHERE CHAR_LENGTH(p.content_text) < 1
  AND p.score < 1

UNION

SELECT 2 AS counter,
            COUNT(*) AS countOf,
            a.countOf,
            b.countOf
FROM posts p
INNER JOIN (
  SELECT 2 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 1 AND 50
    AND p.score BETWEEN 1 AND 10
) AS a ON a.tmpid = 2
INNER JOIN (
  SELECT 2 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 51 AND 100
    AND p.score BETWEEN 1 AND 10
) AS b ON b.tmpid = 2
WHERE CHAR_LENGTH(p.content_text) < 1
  AND p.score BETWEEN 1 AND 10

-- ...
