-- Each row has a counter ID

-- TURN THIS INTO GENERATED BY JAVASCRIPT

SELECT ${counter} AS counter,
            COUNT(*) AS countOf,
            a.countOf,
            b.countOf
FROM posts p
INNER JOIN (
  SELECT ${counter} AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 1 AND 50
    AND p.score < 1
) AS a ON a.tmpid = ${counter}
INNER JOIN (
  SELECT 1 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 51 AND 100
    AND p.score < 1
) AS b ON b.tmpid = ${counter}
WHERE CHAR_LENGTH(p.content_text) < 1
  AND p.score < 1

UNION

SELECT 2 AS counter,
            COUNT(*) AS countOf,
            a.countOf,
            b.countOf
FROM posts p
INNER JOIN (
  SELECT 2 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 1 AND 50
    AND p.score BETWEEN 1 AND 10
) AS a ON a.tmpid = 2
INNER JOIN (
  SELECT 2 AS tmpid,
         COUNT(*) AS countOf
  FROM posts p
  WHERE CHAR_LENGTH(p.content_text) BETWEEN 51 AND 100
    AND p.score BETWEEN 1 AND 10
) AS b ON b.tmpid = 2
WHERE CHAR_LENGTH(p.content_text) < 1
  AND p.score BETWEEN 1 AND 10

-- ...
